dep2E/Models/Empleado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dep2E.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Nominas = new HashSet<Nomina>();
        }
    
        public int idEmpleado { get; set; }
        public int idDepartamento { get; set; }
        public string nombre_Empleado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public double sueldo { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nominas { get; set; }
    }
}

dep2E/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dep2E.Models;

namespace dep2E.Controllers
{
    public class EmpleadosController : Controller
    {
        private dep2EEntities db = new dep2EEntities();

        // GET: Empleados
        public ActionResult Index()
        {
            var empleados = db.Empleados.Include(e => e.Departamento);
            return View(empleados.ToList());
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            ViewBag.idDepartamento = new SelectList(db.Departamentos, "idDepartamento", "nombre_Departamento");
            return View();
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idEmpleado,idDepartamento,nombre_Empleado,Estado,sueldo")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Empleados.Add(empleado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idDepartamento = new SelectList(db.Departamentos, "idDepartamento", "nombre_Departamento", empleado.idDepartamento);
            return View(empleado);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDepartamento = new SelectList(db.Departamentos, "idDepartamento", "nombre_Departamento", empleado.idDepartamento);
            return View(empleado);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idEmpleado,idDepartamento,nombre_Empleado,Estado,sueldo")] Empleado empleado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDepartamento = new SelectList(db.Departamentos, "idDepartamento", "nombre_Departamento", empleado.idDepartamento);
            return View(empleado);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleado empleado = db.Empleados.Find(id);
            if (empleado == null)
            {
                return HttpNotFound();
            }
            return View(empleado);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleado empleado = db.Empleados.Find(id);
            db.Empleados.Remove(empleado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BuscarPorEmpleado(string Nombre)
        {
            var busqueda = from s in db.Empleados select s;
            if (!String.IsNullOrEmpty(Nombre))
            {
                busqueda = busqueda.Where(s => s.nombre_Empleado.Contains(Nombre));
            }
            return View(busqueda.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dep2E/Controllers/NominasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dep2E.Models;

namespace dep2E.Controllers
{
    public class NominasController : Controller
    {
        private dep2EEntities db = new dep2EEntities();

        // GET: Nominas
        public ActionResult Index()
        {
            var nominas = db.Nominas.Include(n => n.Empleado).Where(n => n.Empleado.Estado == true);
            return View(nominas.ToList());
        }

        // GET: Nominas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // GET: Nominas/Create
        public ActionResult Create()
        {
            ViewBag.idEmpleado = new SelectList(db.Empleados, "idEmpleado", "nombre_Empleado");
            return View();
        }

        // POST: Nominas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idNomina,idEmpleado,sueldo_por_dia,dias_trabajados,sueldo_quincenal,fecha")] Nomina nomina)
        {
            if (ModelState.IsValid)
            {
                db.Nominas.Add(nomina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idEmpleado = new SelectList(db.Empleados, "idEmpleado", "nombre_Empleado", nomina.idEmpleado);
            return View(nomina);
        }

        // GET: Nominas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmpleado = new SelectList(db.Empleados, "idEmpleado", "nombre_Empleado", nomina.idEmpleado);
            return View(nomina);
        }

        // POST: Nominas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idNomina,idEmpleado,sueldo_por_dia,dias_trabajados,sueldo_quincenal,fecha")] Nomina nomina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nomina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idEmpleado = new SelectList(db.Empleados, "idEmpleado", "nombre_Empleado", nomina.idEmpleado);
            return View(nomina);
        }

        // GET: Nominas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        // POST: Nominas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nomina nomina = db.Nominas.Find(id);
            db.Nominas.Remove(nomina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult BuscarNominaPorFecha(String Fecha)
        {
            ViewBag.Fecha = new SelectList(db.Nominas, "Fecha", "Fecha");

            var busqueda = from s in db.Nominas select s;

            if (!String.IsNullOrEmpty(Fecha))
            {
                busqueda = busqueda.Where(s => s.fecha == Fecha);
            }
            return View(busqueda.ToList());
        }

        public ActionResult NominaPorEmpleado(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nomina nomina = db.Nominas.Find(id);
            if (nomina == null)
            {
                return HttpNotFound();
            }
            return View(nomina);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

dep2E/Views/Empleados/BuscarPorEmpleado.cshtml
@model IEnumerable<dep2E.Models.Empleado>
@{
    ViewBag.Title = "BuscarPorEmpleado";
}

<h2>BuscarPorEmpleado</h2>

@using (Html.BeginForm("BuscarPorEmpleado", "Empleados", FormMethod.Get))
{
    <p>
        Buscar por nombre:
    </p>
    <div class="form-group">
        @Html.TextBox("nombre", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <input type="submit" value="Buscar" class="btn btn-default" />
        @Html.ActionLink("Cancelar", "Index")
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre_Empleado)
        </th>
        <th>Opcion</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nombre_Empleado)
            </td>

            <td>
                @Html.ActionLink("Ver Nomina", "NominaPorEmpleado", "Nominas", new { id = item.idEmpleado }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>

dep2E/Views/Empleados/Create.cshtml
@model dep2E.Models.Empleado

@{
    ViewBag.Title = "Empleado";
}

<h2>Crear</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idDepartamento, "Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idDepartamento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idDepartamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_Empleado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sueldo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
                @Html.ActionLink("Cancelar", "Index")
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dep2E/Views/Empleados/Delete.cshtml
@model dep2E.Models.Empleado

@{
    ViewBag.Title = "Empleado";
}

<h2>Eliminar</h2>

<h3>¿Estás seguro de eliminar este registro?</h3>
<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre_Empleado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre_Empleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sueldo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sueldo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento.nombre_Departamento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Departamento.nombre_Departamento)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Confirmar" class="btn btn-default" />
            @Html.ActionLink("Cancelar", "Index")
        </div>
    }
</div>

dep2E/Views/Empleados/Details.cshtml
@model dep2E.Models.Empleado

@{
    ViewBag.Title = "Empleado";
}

<h2>Detalle</h2>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre_Empleado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.nombre_Empleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sueldo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.sueldo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Departamento.nombre_Departamento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Departamento.nombre_Departamento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.idEmpleado }, new { @class = "btn btn-default" })
    @Html.ActionLink("Cancelar", "Index")
</p>

dep2E/Views/Empleados/Edit.cshtml
@model dep2E.Models.Empleado

@{
    ViewBag.Title = "Empleados";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleado</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idEmpleado)

        <div class="form-group">
            @Html.LabelFor(model => model.idDepartamento, "Departamento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idDepartamento", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idDepartamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_Empleado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_Empleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_Empleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sueldo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sueldo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
                @Html.ActionLink("Cancelar", "Index")

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dep2E/Views/Empleados/Index.cshtml
@model IEnumerable<dep2E.Models.Empleado>

@{
    ViewBag.Title = "Empleados";
}

<h2>Lista de Empleados</h2>

<p>
    @Html.ActionLink("Crear nuevo", "Create", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Buscar por Empleado", "BuscarPorEmpleado", "Empleados", null, new { @class = "btn btn-default" })
</p>
@{
    int i = 1;
}

<table class="table">
    @if (Model.Count() != 0)
    {
        <tr>
            <th>#</th>
            <th>
                @Html.DisplayNameFor(model => model.nombre_Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento.nombre_Departamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.sueldo)
            </th>
            <th>Opciones</th>
        </tr>
        foreach (var item in Model)
        {
            <tr>
                <td>@i</td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre_Empleado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departamento.nombre_Departamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.sueldo)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.idEmpleado }, new { @class = "btn btn-primary" })
                    @Html.ActionLink("Detalle", "Details", new { id = item.idEmpleado }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.idEmpleado }, new { @class = "btn btn-warning" })
                </td>
            </tr>
            i++;
        }
    }
    else
    {
        <tr>
            <td colspan="3" align="center"><h5>No hay Empleados registrados</h5></td>
        </tr>
    }
</table>
@Html.ActionLink("Regresar a inicio", "Index", "Home")